# Generated by Django 2.2.2 on 2019-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colID', models.CharField(max_length=100)),
                ('colName', models.CharField(max_length=100)),
                ('colExh', models.CharField(max_length=100)),
                ('colMods', models.CharField(max_length=100)),
            ],
        ),
    ]
