# Generated by Django 2.2.2 on 2019-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCalls', '0002_auto_20190604_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='colID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
