# Generated by Django 2.2.2 on 2019-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCalls', '0003_auto_20190604_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='colExh',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='colMods',
            field=models.TextField(blank=True),
        ),
    ]
