# Generated by Django 2.2.2 on 2019-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAnswers',
            fields=[
                ('colID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('colAns', models.TextField()),
            ],
        ),
    ]
