# Generated by Django 2.2.2 on 2019-07-01 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0002_collectionanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionanswers',
            name='colPar',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
