# Generated by Django 2.2.2 on 2019-07-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0003_collectionanswers_colpar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftParticipant',
            fields=[
                ('parID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('parStories', models.TextField()),
                ('parChapters', models.TextField()),
                ('parExhibits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GiftAnswers',
            fields=[
                ('giftID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('giftWord', models.TextField()),
                ('giftFree', models.TextField()),
                ('giftArou', models.FloatField()),
                ('giftVael', models.FloatField()),
                ('parID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBStorage.Participant')),
            ],
        ),
    ]
