# Generated by Django 2.2.2 on 2019-07-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0004_giftanswers_giftparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftanswers',
            name='modID',
            field=models.CharField(default='mod22', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='giftFree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='giftWord',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='parID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBStorage.GiftParticipant'),
        ),
    ]
