# Generated by Django 2.2.2 on 2019-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0005_auto_20190705_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftanswers',
            name='giftID',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
