# Generated by Django 2.2.3 on 2019-07-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0006_auto_20190705_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftanswers',
            name='parID',
            field=models.CharField(max_length=100),
        ),
    ]
