# Generated by Django 2.2.3 on 2019-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0009_auto_20190709_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftanswers',
            name='giftArou',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='giftFree',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='giftVael',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='giftWord',
            field=models.TextField(),
        ),
    ]
