# Generated by Django 2.2.3 on 2019-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0010_auto_20190710_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftanswers',
            name='modID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='parID',
            field=models.TextField(),
        ),
    ]
