# Generated by Django 2.2.3 on 2019-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0012_auto_20190710_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftanswers',
            name='giftFree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='giftWord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='modID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='giftanswers',
            name='parID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
