# Generated by Django 2.2.3 on 2019-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBStorage', '0014_auto_20190710_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
            ],
        ),
    ]
